--- #YAML:1.0
name:                     Text-Demoroniser
version:                  0.03
abstract:                 A text filter that allows you to demoronise a string.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  Encode::ZapCP1252:      0
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.13
build_requires:
  Test::More:             0.70
  IO::File:               0

provides:
  Text::Demoroniser:
    file:     lib/Text/Demoroniser.pm
    version:  0.03
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Demoroniser
  repository: http://github.com/barbie/Text-Demoroniser.git

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
